# -*- coding: utf-8 -*-
"""
Skill Hub catalog — curated registry of third-party agent skills.

Skills follow the open Agent Skills standard (https://agentskills.io).
Each skill is a SKILL.md file that any compatible agent can discover and use.

The catalog is versioned with the codebase; the database stores only
per-agent skill assignments (WorkspaceMember.enabled_skills JSONB).
"""

from typing import Dict, List, Optional, Set

SKILL_CATALOG: List[dict] = [
    # -------------------------------------------------------------------------
    # AI & ML
    # -------------------------------------------------------------------------
    {
        "id": "claude-api",
        "name": "Claude API",
        "description": "Build, debug, and optimize Claude API / Anthropic SDK apps with prompt caching",
        "category": "ai-ml",
        "icon": "brain",
        "source_repo": "anthropics/skills",
        "source_path": "skills/claude-api",
        "author": "Anthropic",
    },
    {
        "id": "openai-sdk",
        "name": "OpenAI SDK",
        "description": "Integrate OpenAI APIs — GPT, embeddings, function calling, DALL-E, Whisper",
        "category": "ai-ml",
        "icon": "sparkles",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/openai-sdk",
        "author": "Community",
    },
    {
        "id": "langchain",
        "name": "LangChain",
        "description": "Build LLM-powered apps — RAG pipelines, agents, chains, vector stores",
        "category": "ai-ml",
        "icon": "link",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/langchain",
        "author": "Community",
    },
    {
        "id": "mcp-builder",
        "name": "MCP Builder",
        "description": "Create MCP servers that enable LLMs to interact with external services",
        "category": "ai-ml",
        "icon": "plug",
        "source_repo": "anthropics/skills",
        "source_path": "skills/mcp-builder",
        "author": "Anthropic",
    },
    {
        "id": "skill-creator",
        "name": "Skill Creator",
        "description": "Create, modify, and benchmark agent skills with eval-driven iteration",
        "category": "ai-ml",
        "icon": "wand-2",
        "source_repo": "anthropics/skills",
        "source_path": "skills/skill-creator",
        "author": "Anthropic",
    },
    {
        "id": "ai-sdk",
        "name": "Vercel AI SDK",
        "description": "Build AI-powered apps with the Vercel AI SDK — streaming, tool use, RAG",
        "category": "ai-ml",
        "icon": "cpu",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/ai-sdk",
        "author": "Community",
    },
    # -------------------------------------------------------------------------
    # Frontend
    # -------------------------------------------------------------------------
    {
        "id": "nextjs",
        "name": "Next.js",
        "description": "Production-grade React apps with App Router, Server Components, and Server Actions",
        "category": "frontend",
        "icon": "layout",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/nextjs",
        "author": "Community",
    },
    {
        "id": "angular",
        "name": "Angular",
        "description": "TypeScript-based frontend framework — components, DI, RxJS, routing, forms",
        "category": "frontend",
        "icon": "triangle",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/angular",
        "author": "Community",
    },
    {
        "id": "vue",
        "name": "Vue.js",
        "description": "Progressive JavaScript framework — Composition API, reactive refs, SFCs",
        "category": "frontend",
        "icon": "hexagon",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/vue",
        "author": "Community",
    },
    {
        "id": "svelte",
        "name": "Svelte",
        "description": "Svelte 5 and SvelteKit 2 — runes, snippets, stores, compiled to vanilla JS",
        "category": "frontend",
        "icon": "flame",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/svelte",
        "author": "Community",
    },
    {
        "id": "tailwindcss",
        "name": "Tailwind CSS",
        "description": "Utility-first CSS v4 — layout, spacing, typography, responsive design tokens",
        "category": "frontend",
        "icon": "paintbrush",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/tailwindcss",
        "author": "Community",
    },
    {
        "id": "frontend-design",
        "name": "Frontend Design",
        "description": "Create distinctive, production-grade UIs that avoid generic AI aesthetics",
        "category": "frontend",
        "icon": "palette",
        "source_repo": "anthropics/skills",
        "source_path": "skills/frontend-design",
        "author": "Anthropic",
    },
    {
        "id": "accessibility-auditor",
        "name": "Accessibility Auditor",
        "description": "Audit web pages for WCAG 2.2 — contrast, keyboard nav, screen readers",
        "category": "frontend",
        "icon": "eye",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/accessibility-auditor",
        "author": "Community",
    },
    # -------------------------------------------------------------------------
    # Backend
    # -------------------------------------------------------------------------
    {
        "id": "fastapi",
        "name": "FastAPI",
        "description": "Modern Python API framework — type hints, Pydantic, async, auto OpenAPI docs",
        "category": "backend",
        "icon": "zap",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/fastapi",
        "author": "Community",
    },
    {
        "id": "django",
        "name": "Django",
        "description": "Batteries-included Python web framework — ORM, admin, auth, templates",
        "category": "backend",
        "icon": "server",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/django",
        "author": "Community",
    },
    {
        "id": "flask",
        "name": "Flask",
        "description": "Lightweight Python micro web framework — Jinja2, Werkzeug, extensions",
        "category": "backend",
        "icon": "flask-conical",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/flask",
        "author": "Community",
    },
    {
        "id": "graphql",
        "name": "GraphQL",
        "description": "Build and consume GraphQL APIs — schemas, resolvers, subscriptions, federation",
        "category": "backend",
        "icon": "share-2",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/graphql",
        "author": "Community",
    },
    {
        "id": "grpc",
        "name": "gRPC",
        "description": "High-performance RPC with Protocol Buffers — streaming, interceptors, health checks",
        "category": "backend",
        "icon": "arrow-left-right",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/grpc",
        "author": "Community",
    },
    {
        "id": "rest-api",
        "name": "REST API Design",
        "description": "Design RESTful APIs — resource modeling, status codes, pagination, OpenAPI docs",
        "category": "backend",
        "icon": "route",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/rest-api",
        "author": "Community",
    },
    {
        "id": "celery",
        "name": "Celery",
        "description": "Background tasks in Python — async workers, periodic jobs, task queues",
        "category": "backend",
        "icon": "loader",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/celery",
        "author": "Community",
    },
    {
        "id": "rabbitmq",
        "name": "RabbitMQ",
        "description": "Message broker — queues, exchanges, routing, dead-letter, RPC patterns",
        "category": "backend",
        "icon": "mail",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/rabbitmq",
        "author": "Community",
    },
    {
        "id": "kafka",
        "name": "Apache Kafka",
        "description": "Event-driven streaming — pub/sub, event sourcing, real-time data pipelines",
        "category": "backend",
        "icon": "activity",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/kafka",
        "author": "Community",
    },
    {
        "id": "rate-limiter",
        "name": "Rate Limiter",
        "description": "API rate limiting — token bucket, sliding window, Redis-backed distributed counters",
        "category": "backend",
        "icon": "shield",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/rate-limiter",
        "author": "Community",
    },
    # -------------------------------------------------------------------------
    # Database
    # -------------------------------------------------------------------------
    {
        "id": "postgresql",
        "name": "PostgreSQL",
        "description": "Schema design, queries, JSONB, full-text search, RLS, performance tuning",
        "category": "database",
        "icon": "database",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/postgresql",
        "author": "Community",
    },
    {
        "id": "mongodb",
        "name": "MongoDB",
        "description": "Document schemas, aggregation pipelines, indexes, Atlas Search, vector search",
        "category": "database",
        "icon": "leaf",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/mongodb",
        "author": "Community",
    },
    {
        "id": "redis",
        "name": "Redis",
        "description": "In-memory data store — caching, pub/sub, streams, rate limiting, leaderboards",
        "category": "database",
        "icon": "layers",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/redis",
        "author": "Community",
    },
    {
        "id": "prisma",
        "name": "Prisma",
        "description": "TypeScript ORM — declarative schema, type-safe client, zero-downtime migrations",
        "category": "database",
        "icon": "box",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/prisma",
        "author": "Community",
    },
    {
        "id": "supabase",
        "name": "Supabase",
        "description": "Postgres backend — auth, real-time subscriptions, storage, edge functions, RLS",
        "category": "database",
        "icon": "zap",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/supabase",
        "author": "Community",
    },
    {
        "id": "firebase",
        "name": "Firebase",
        "description": "Google's app platform — Firestore, auth, Cloud Functions, hosting, analytics",
        "category": "database",
        "icon": "flame",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/firebase",
        "author": "Community",
    },
    # -------------------------------------------------------------------------
    # DevOps & Infrastructure
    # -------------------------------------------------------------------------
    {
        "id": "github-actions",
        "name": "GitHub Actions",
        "description": "CI/CD pipelines — workflows, matrix builds, caching, secrets, reusable workflows",
        "category": "devops",
        "icon": "git-branch",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/github-actions",
        "author": "Community",
    },
    {
        "id": "ansible",
        "name": "Ansible",
        "description": "Configuration management — playbooks, inventory, roles, Vault, multi-server deployments",
        "category": "devops",
        "icon": "terminal",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/ansible",
        "author": "Community",
    },
    {
        "id": "nginx",
        "name": "Nginx",
        "description": "Web server, reverse proxy, load balancer — TLS, caching, rate limiting, headers",
        "category": "devops",
        "icon": "server",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/nginx",
        "author": "Community",
    },
    {
        "id": "cloudflare",
        "name": "Cloudflare",
        "description": "CDN, DDoS protection, DNS, SSL, WAF, Workers — protect and accelerate sites",
        "category": "devops",
        "icon": "cloud",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/cloudflare",
        "author": "Community",
    },
    {
        "id": "sentry",
        "name": "Sentry",
        "description": "Error monitoring, APM, session replay — track crashes and performance in production",
        "category": "devops",
        "icon": "bug",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/sentry",
        "author": "Community",
    },
    {
        "id": "datadog",
        "name": "Datadog",
        "description": "Infrastructure monitoring, APM, log management, dashboards, alerting",
        "category": "devops",
        "icon": "bar-chart-2",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/datadog",
        "author": "Community",
    },
    # -------------------------------------------------------------------------
    # Testing
    # -------------------------------------------------------------------------
    {
        "id": "jest",
        "name": "Jest",
        "description": "JavaScript testing — unit, integration, snapshot, mocking, code coverage",
        "category": "testing",
        "icon": "check-circle",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/jest",
        "author": "Community",
    },
    {
        "id": "pytest",
        "name": "pytest",
        "description": "Python testing — fixtures, mocking, async tests, coverage, TDD",
        "category": "testing",
        "icon": "check-circle",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/pytest",
        "author": "Community",
    },
    {
        "id": "cypress",
        "name": "Cypress",
        "description": "End-to-end web testing — component tests, CI parallelization, custom commands",
        "category": "testing",
        "icon": "monitor",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/cypress",
        "author": "Community",
    },
    {
        "id": "webapp-testing",
        "name": "Webapp Testing",
        "description": "Test local web apps with Playwright — screenshots, browser logs, UI verification",
        "category": "testing",
        "icon": "monitor-check",
        "source_repo": "anthropics/skills",
        "source_path": "skills/webapp-testing",
        "author": "Anthropic",
    },
    {
        "id": "ab-test-setup",
        "name": "A/B Testing",
        "description": "Plan, design, and implement A/B tests — hypotheses, variants, measurement",
        "category": "testing",
        "icon": "split",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/ab-test-setup",
        "author": "Community",
    },
    {
        "id": "security-audit",
        "name": "Security Audit",
        "description": "Scan for vulnerabilities — OWASP Top 10, secrets, CVEs, SQL injection, XSS",
        "category": "security",
        "icon": "shield-alert",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/security-audit",
        "author": "Community",
    },
    # -------------------------------------------------------------------------
    # Integrations & SaaS
    # -------------------------------------------------------------------------
    {
        "id": "airtable",
        "name": "Airtable",
        "description": "Airtable API — bases, tables, records, fields, views, webhooks, OAuth",
        "category": "integrations",
        "icon": "table",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/airtable",
        "author": "Community",
    },
    {
        "id": "notion",
        "name": "Notion",
        "description": "Notion API — databases, pages, blocks, comments, search, OAuth",
        "category": "integrations",
        "icon": "book-open",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/notion",
        "author": "Community",
    },
    {
        "id": "jira",
        "name": "Jira",
        "description": "Project management — issues, workflows, boards, sprints, JQL, automation",
        "category": "integrations",
        "icon": "ticket",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/jira",
        "author": "Community",
    },
    {
        "id": "linear",
        "name": "Linear",
        "description": "Issue tracking — projects, cycles, triage, GraphQL API, GitHub sync",
        "category": "integrations",
        "icon": "circle-dot",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/linear",
        "author": "Community",
    },
    {
        "id": "stripe",
        "name": "Stripe Payments",
        "description": "Complete payment flow — checkout, subscriptions, invoices, webhooks",
        "category": "integrations",
        "icon": "credit-card",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/stripe",
        "author": "Community",
    },
    {
        "id": "twilio",
        "name": "Twilio",
        "description": "SMS, voice calls, WhatsApp messaging, 2FA verification, IVR systems",
        "category": "integrations",
        "icon": "phone",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/twilio",
        "author": "Community",
    },
    {
        "id": "sendgrid",
        "name": "SendGrid",
        "description": "Transactional and marketing email — templates, tracking, deliverability",
        "category": "integrations",
        "icon": "send",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/sendgrid",
        "author": "Community",
    },
    {
        "id": "shopify",
        "name": "Shopify",
        "description": "E-commerce — Liquid themes, Storefront API, custom apps, Hydrogen headless",
        "category": "integrations",
        "icon": "shopping-bag",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/shopify",
        "author": "Community",
    },
    {
        "id": "wordpress",
        "name": "WordPress",
        "description": "CMS powering 43% of the web — Gutenberg, themes, plugins, REST API, WP-CLI",
        "category": "integrations",
        "icon": "file-text",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/wordpress",
        "author": "Community",
    },
    {
        "id": "woocommerce",
        "name": "WooCommerce",
        "description": "WordPress e-commerce — products, orders, checkout, payment gateways",
        "category": "integrations",
        "icon": "shopping-cart",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/woocommerce",
        "author": "Community",
    },
    {
        "id": "contentful",
        "name": "Contentful",
        "description": "API-first CMS — content models, delivery API, localization, rich text, webhooks",
        "category": "integrations",
        "icon": "layout-grid",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/contentful",
        "author": "Community",
    },
    {
        "id": "sanity",
        "name": "Sanity",
        "description": "Structured content platform — GROQ queries, Studio, Portable Text, Next.js",
        "category": "integrations",
        "icon": "database",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/sanity",
        "author": "Community",
    },
    {
        "id": "zapier",
        "name": "Zapier",
        "description": "No-code automation — connect apps, sync data, automate workflows between SaaS",
        "category": "integrations",
        "icon": "workflow",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/zapier",
        "author": "Community",
    },
    {
        "id": "analytics-tracking",
        "name": "Analytics Tracking",
        "description": "Set up GA4, conversion tracking, event tracking, UTM parameters, GTM",
        "category": "integrations",
        "icon": "line-chart",
        "source_repo": "TerminalSkills/skills",
        "source_path": "skills/analytics-tracking",
        "author": "Community",
    },
    # -------------------------------------------------------------------------
    # Documents & Productivity
    # -------------------------------------------------------------------------
    {
        "id": "docx",
        "name": "Word Documents",
        "description": "Create, read, edit .docx files — TOC, headers, page numbers, letterheads",
        "category": "documents",
        "icon": "file-text",
        "source_repo": "anthropics/skills",
        "source_path": "skills/docx",
        "author": "Anthropic",
    },
    {
        "id": "xlsx",
        "name": "Spreadsheets",
        "description": "Read, write, format .xlsx files — formulas, charts, data cleaning, pivot tables",
        "category": "documents",
        "icon": "table-2",
        "source_repo": "anthropics/skills",
        "source_path": "skills/xlsx",
        "author": "Anthropic",
    },
    {
        "id": "pptx",
        "name": "Presentations",
        "description": "Create and edit .pptx slide decks — layouts, speaker notes, templates",
        "category": "documents",
        "icon": "presentation",
        "source_repo": "anthropics/skills",
        "source_path": "skills/pptx",
        "author": "Anthropic",
    },
    {
        "id": "pdf",
        "name": "PDF Processing",
        "description": "Read, merge, split, watermark, OCR, encrypt PDFs — forms and image extraction",
        "category": "documents",
        "icon": "file",
        "source_repo": "anthropics/skills",
        "source_path": "skills/pdf",
        "author": "Anthropic",
    },
    {
        "id": "doc-coauthoring",
        "name": "Doc Co-Authoring",
        "description": "Structured workflow for co-authoring docs, specs, proposals, and decision docs",
        "category": "documents",
        "icon": "pen-tool",
        "source_repo": "anthropics/skills",
        "source_path": "skills/doc-coauthoring",
        "author": "Anthropic",
    },
    # -------------------------------------------------------------------------
    # SenseNova Skills (OpenSenseNova)
    # -------------------------------------------------------------------------
    {
        "id": "sn-deep-research",
        "name": "SenseNova Deep Research",
        "description": "Full-pipeline deep research — planning, multi-source evidence, synthesis, and report generation",
        "category": "ai-ml",
        "icon": "search",
        "source_repo": "OpenSenseNova/SenseNova-Skills",
        "source_path": "skills/sn-deep-research",
        "author": "SenseNova",
    },
    {
        "id": "sn-infographic",
        "name": "SenseNova Infographic",
        "description": "Generate professional infographics with various layouts and visual styles",
        "category": "documents",
        "icon": "image",
        "source_repo": "OpenSenseNova/SenseNova-Skills",
        "source_path": "skills/sn-infographic",
        "author": "SenseNova",
    },
    {
        "id": "sn-ppt-entry",
        "name": "SenseNova PPT",
        "description": "AI-powered presentation creation — standard and creative modes with full-page visuals",
        "category": "documents",
        "icon": "presentation",
        "source_repo": "OpenSenseNova/SenseNova-Skills",
        "source_path": "skills/sn-ppt-entry",
        "author": "SenseNova",
    },
    {
        "id": "sn-da-excel-workflow",
        "name": "SenseNova Excel Analysis",
        "description": "End-to-end Excel data analysis — cleaning, filtering, aggregation, charts, and export",
        "category": "documents",
        "icon": "table",
        "source_repo": "OpenSenseNova/SenseNova-Skills",
        "source_path": "skills/sn-da-excel-workflow",
        "author": "SenseNova",
    },
    {
        "id": "sn-image-base",
        "name": "SenseNova Image Gen",
        "description": "Image generation, recognition (VLM), and text optimization APIs",
        "category": "ai-ml",
        "icon": "image",
        "source_repo": "OpenSenseNova/SenseNova-Skills",
        "source_path": "skills/sn-image-base",
        "author": "SenseNova",
    },
    {
        "id": "sn-md-to-html-report",
        "name": "SenseNova HTML Report",
        "description": "Convert Markdown research reports to polished HTML with charts and styling",
        "category": "documents",
        "icon": "file-text",
        "source_repo": "OpenSenseNova/SenseNova-Skills",
        "source_path": "skills/sn-md-to-html-report",
        "author": "SenseNova",
    },
]

# Keep the workspace-module helpers for backward compatibility with the launcher
_WORKSPACE_MODULES = {"files", "browser", "tunnel", "todos", "timers", "routines", "knowledge"}


def get_catalog() -> List[dict]:
    """Return the full third-party skill catalog."""
    return list(SKILL_CATALOG)


def find_skill(skill_id: str) -> Optional[dict]:
    """Look up a catalog entry by id. Returns ``None`` if unknown."""
    for entry in SKILL_CATALOG:
        if entry.get("id") == skill_id:
            return entry
    return None


def get_skill_defaults() -> Dict[str, bool]:
    """Return ``{module: True}`` for all workspace modules (backward compat)."""
    return {m: True for m in _WORKSPACE_MODULES}


def skills_to_disabled_modules(enabled_skills: Optional[Dict[str, bool]]) -> Set[str]:
    """Convert a per-agent ``enabled_skills`` JSONB dict to a ``disabledModules`` Set.

    Only processes workspace module keys (files, browser, etc.), not third-party skills.
    ``None`` (no overrides) -> empty set (everything enabled).
    """
    if not enabled_skills:
        return set()

    disabled: Set[str] = set()
    for module in _WORKSPACE_MODULES:
        if enabled_skills.get(module) is False:
            disabled.add(module)
    return disabled
