"""catchup_missing_tables

Revision ID: 1c617c141e29
Revises: 007
Create Date: 2026-04-23 16:10:02.920687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c617c141e29'
down_revision: Union[str, Sequence[str], None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_usage',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tab_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('opened_by', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_browser_usage_opened_by', 'browser_usage', ['opened_by'], unique=False)
    op.create_index('idx_browser_usage_started', 'browser_usage', ['started_at'], unique=False)
    op.create_index('idx_browser_usage_workspace', 'browser_usage', ['workspace_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Text(), nullable=False),
    sa.Column('channel_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_workspace_status', 'files', ['workspace_id', 'status'], unique=False)
    op.create_table('browser_tabs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('shared_with', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('live_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['browser_contexts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_browser_tabs_workspace_status', 'browser_tabs', ['workspace_id', 'status'], unique=False)
    op.alter_column('browser_contexts', 'shared_with',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.add_column('channels', sa.Column('title_manually_set', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('channels', sa.Column('resume_from', sa.Text(), nullable=True))
    op.alter_column('channels', 'starred',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('workspace_members', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_members', 'description')
    op.alter_column('channels', 'starred',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('channels', 'resume_from')
    op.drop_column('channels', 'title_manually_set')
    op.alter_column('browser_contexts', 'shared_with',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_index('idx_browser_tabs_workspace_status', table_name='browser_tabs')
    op.drop_table('browser_tabs')
    op.drop_index('idx_files_workspace_status', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_browser_usage_workspace', table_name='browser_usage')
    op.drop_index('idx_browser_usage_started', table_name='browser_usage')
    op.drop_index('idx_browser_usage_opened_by', table_name='browser_usage')
    op.drop_table('browser_usage')
    # ### end Alembic commands ###
